version: '3.8'

services:

  booking_manager:
    restart: on-failure
    image: bm
    depends_on:
      - mongodb
    build: .
    command: node src/index.js
    ports:
      - 8080:8080
    volumes:
      - .:${APPLICATION_ROOT_PATH}
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_AUTH_SOURCE=${DB_AUTH_SOURCE}

  mongodb:
    image : mongo
    container_name: mongodb
    restart: on-failure
    volumes:
      - ./db/mongodb/:/data/db/
      - ./init-database-scripts:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    healthcheck:
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 3
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
    restart: unless-stopped

